# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - iqengineweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
        env:
          CI: false

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip

  deploy-to-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Staging'
      url: ${{ steps.deploy-to-staging.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Staging Environment'
        id: deploy-to-staging
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'iqengineweb'
          slot-name: 'staging'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_Staging }}
          package: .
  
  selenium-tests:
    name: Run Selenium Tests
    runs-on: ubuntu-latest
    needs: deploy-to-staging
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Run Selenium Tests
        env:
          STAGING_URL: https://iqengineweb-staging.azurewebsites.net/
        run: |
          cd tests
          pip install -r requirements.txt
          python main.py

  release-to-prod:
    name: Release to Prod
    runs-on: ubuntu-latest
    needs: selenium-tests
    environment:
      name: 'Production'
      url: ${{ steps.release-to-prod.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Prod'
        id: release-to-prod
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'iqengineweb'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_50c7b335d29046f98adf66cde1936d40 }}
          package: .