# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy To PR

on:
  pull_request:
    # only runs on PRs that target main
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install and build
        working-directory: client
        run: |
          npm install
          npm run build --if-present
        env:
          CI: false
          VITE_CONNECTION_INFO: '${{ secrets.VITE_CONNECTION_INFO }}'
          VITE_IQENGINE_APP_VERSION: '$${{ secrets.VITE_IQENGINE_APP_VERSION }}'
          VITE_GOOGLE_ANALYTICS_KEY: '${{ secrets.VITE_GOOGLE_ANALYTICS_KEY }}'
          VITE_DETECTOR_ENDPOINT: '${{ secrets.VITE_DETECTOR_ENDPOINT }}'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: client/build/

  deploy-to-most-recent-pr-slot:
    if: github.event.pull_request.head.repo.full_name == 'IQEngine/IQEngine'
    name: Deploy to Most Recent PR Slot
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Most Recent PR'
      url: ${{ steps.deploy-to-most-recent-pr-slot.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Most Recent PR Slot'
        id: deploy-to-most-recent-pr-slot
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'iqengineweb'
          slot-name: 'most-recent-pr'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_Most_Recent_PR }}
          package: .
  